"""
Response Builder for JKYog WhatsApp Bot
Rohan Kothapalli - Week 3 Assignment

Orchestrates bot responses by routing to appropriate handlers based on intent
and integrating with all teammate modules (knowledge base, database, integrations).
Responses are generated by Gemini using knowledge base content as context,
with hardcoded fallbacks when the API is unavailable.
"""

import os
from typing import Dict, Optional

from .intent_classifier import classify_intent
from .entity_extractor import extract_entities

try:
    from google import genai
    from google.genai import types as genai_types
    _GOOGLE_AVAILABLE = True
except ImportError:
    _GOOGLE_AVAILABLE = False

try:
    from ..knowledge_base.ingestion import search_kb
except ImportError:
    print("Warning: knowledge_base module not found")
    def search_kb(query, top_k=3):
        return []

try:
    from ..integrations.google_maps import get_temple_directions_from_user_location
except ImportError:
    print("Warning: google_maps integration not found")
    def get_temple_directions_from_user_location(user_location, temple_address, mode="driving"):
        return f"Directions from {user_location} to {temple_address} (integration unavailable)"

try:
    from ..integrations.stripe import get_donation_link
except ImportError:
    print("Warning: stripe integration not found")
    def get_donation_link(temple_slug=None):
        return "https://buy.stripe.com/test_default"

try:
    from ..integrations.calendar import get_upcoming_events, get_events_on_date
except ImportError:
    print("Warning: calendar integration not found")
    def get_upcoming_events(limit=5):
        return []
    def get_events_on_date(date_str):
        return []


TEMPLE_ADDRESS = "1450 North Watters Road, Allen, TX 75013"
TEMPLE_NAME = "JKYog Radha Krishna Temple"

_BOT_SYSTEM_PROMPT = """You are a helpful WhatsApp assistant for JKYog Radha Krishna Temple located in Allen, Texas.

Your tone is warm, concise, and spiritually uplifting. You represent the temple with care and respect.

Rules:
- Use the provided context to answer accurately. Do not make up information.
- Keep responses under 250 words and easy to read on a phone screen.
- Use simple bullet points with • (not markdown headers or bold).
- If the context does not contain enough information, be honest and direct the user to call (469) 606-3119 or visit jkyog.org.
- Never mention that you are using a knowledge base or AI."""


def _generate_with_gemini(user_message: str, context: str) -> str | None:
    """
    Generate a conversational response using Gemini with the given context.
    Returns None if Gemini is unavailable or errors.
    """
    if not _GOOGLE_AVAILABLE or not os.getenv("GOOGLE_API_KEY"):
        return None
    try:
        client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
        prompt = f"Context:\n{context}\n\nUser message: {user_message}"
        response = client.models.generate_content(
            model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
            contents=prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=_BOT_SYSTEM_PROMPT,
                temperature=0.4,
                max_output_tokens=400,
            ),
        )
        return response.text.strip()
    except Exception as exc:
        print(f"Gemini response generation error: {exc}")
        return None


def handle_greeting(user_context: Optional[Dict] = None) -> str:
    context = (
        "The user is greeting the bot. Welcome them warmly and briefly list what the bot can help with: "
        "temple information (location, hours, dress code), event schedules (satsang, bhajans, special events), "
        "directions to the temple, and donation information."
    )
    generated = _generate_with_gemini("Hello", context)
    if generated:
        return generated

    greeting = "Namaste! Welcome to JKYog Radha Krishna Temple.\n\n"
    greeting += "I can help you with:\n"
    greeting += "• Temple information (location, hours, dress code)\n"
    greeting += "• Event schedules (satsang, bhajans, special events)\n"
    greeting += "• Directions to the temple\n"
    greeting += "• Donation information\n\n"
    greeting += "How can I assist you today?"
    return greeting


def handle_faq_query(user_message: str, entities: Dict) -> str:
    results = search_kb(user_message, top_k=3)

    if results:
        context_parts = []
        for r in results:
            if r["type"] == "faq":
                faq = r["payload"]
                context_parts.append(
                    f"Q: {faq.get('question', '')}\nA: {faq.get('answer', '')}"
                )
        if context_parts:
            context = "\n\n".join(context_parts)
            generated = _generate_with_gemini(user_message, context)
            if generated:
                return generated

        # Fallback: return the raw top answer
        top = results[0]
        if top["type"] == "faq":
            faq = top["payload"]
            response = f"{faq.get('answer', '')}\n\n"
            if len(results) > 1:
                response += "Related:\n"
                for r in results[1:3]:
                    if r["type"] == "faq":
                        response += f"• {r['payload'].get('question', '')}\n"
            return response

    return (
        "I don't have specific information about that. "
        "Please contact the temple directly at (469) 606-3119 or visit jkyog.org."
    )


def handle_event_query(user_message: str, entities: Dict) -> str:
    results = search_kb(user_message, top_k=3)
    event_results = [r for r in results if r["type"] == "event"]

    if event_results:
        context_parts = []
        for r in event_results:
            e = r["payload"]
            parts = [f"Event: {e.get('title', '')}"]
            if e.get("description"):
                parts.append(f"Description: {e['description']}")
            if e.get("day"):
                timing = e["day"]
                if e.get("start_time"):
                    timing += f" at {e['start_time']}"
                if e.get("end_time"):
                    timing += f" - {e['end_time']}"
                parts.append(f"When: {timing}")
            if e.get("start_day"):
                parts.append(f"Dates: {e['start_day']} to {e.get('end_day', '')}")
            if e.get("location"):
                parts.append(f"Location: {e['location']}")
            context_parts.append("\n".join(parts))

        context = "\n\n".join(context_parts)
        generated = _generate_with_gemini(user_message, context)
        if generated:
            return generated

        # Fallback: format event list
        response = "Events:\n\n"
        for r in event_results[:3]:
            e = r["payload"]
            response += f"• {e.get('title', 'Event')}\n"
            if e.get("day"):
                response += f"  {e['day']}"
                if e.get("start_time"):
                    response += f" at {e['start_time']}"
                response += "\n"
        return response

    # Try calendar integration
    calendar_events = (
        get_events_on_date(entities["date"])
        if "date" in entities
        else get_upcoming_events(limit=5)
    )
    if calendar_events:
        response = "Upcoming Events:\n\n"
        for event in calendar_events[:3]:
            response += f"• {event.get('summary', 'Event')}\n"
            response += f"  {event.get('start', '')}\n"
        return response

    return (
        "I couldn't find specific event information. "
        "Please check our website at jkyog.org or call (469) 606-3119."
    )


def handle_donation(entities: Dict) -> str:
    donation_link = get_donation_link(temple_slug="dallas")
    context = (
        f"The user wants to donate to JKYog Radha Krishna Temple. "
        f"The donation link is: {donation_link}. "
        f"Donations are tax-deductible and support temple facilities, spiritual programs, and community service."
    )
    generated = _generate_with_gemini("How do I donate?", context)
    if generated:
        return generated

    response = "Thank you for your generous support!\n\n"
    response += f"You can make a donation here:\n{donation_link}\n\n"
    response += "Your contributions help us:\n"
    response += "• Maintain the temple facilities\n"
    response += "• Organize spiritual programs\n"
    response += "• Serve the community\n\n"
    response += "All donations are tax-deductible."
    return response


def handle_directions(user_message: str, entities: Dict) -> str:
    user_location = entities.get("location")
    directions_text = ""

    if user_location:
        directions_text = get_temple_directions_from_user_location(
            user_location=user_location,
            temple_address=TEMPLE_ADDRESS,
        )

    context = (
        f"The user is asking for directions to {TEMPLE_NAME}. "
        f"The address is: {TEMPLE_ADDRESS}. "
        f"Parking is available on-site."
    )
    if directions_text:
        context += f"\n\nDirections details: {directions_text}"

    generated = _generate_with_gemini(user_message, context)
    if generated:
        return generated

    response = f"Directions to {TEMPLE_NAME}:\n\n"
    response += f"Address: {TEMPLE_ADDRESS}\n\n"
    if directions_text:
        response += directions_text
    else:
        response += "The temple is located in Allen, Texas.\n\n"
        response += "Use the address above in your GPS for turn-by-turn directions.\n\n"
        response += "Ample parking is available on-site."
    return response


def handle_unknown(user_message: str) -> str:
    context = (
        "The user sent a message the bot doesn't understand or that is outside the scope of temple assistance. "
        "Politely let them know what the bot can help with: temple information, events, directions, and donations. "
        "Provide the temple contact number (469) 606-3119 and website jkyog.org for other inquiries."
    )
    generated = _generate_with_gemini(user_message, context)
    if generated:
        return generated

    response = "I'm not sure I understood that.\n\n"
    response += "I can help you with:\n"
    response += "• Temple information (location, hours, facilities)\n"
    response += "• Event schedules and timings\n"
    response += "• Directions to the temple\n"
    response += "• Donation information\n\n"
    response += "For other inquiries, please contact:\n"
    response += "(469) 606-3119\n"
    response += "jkyog.org"
    return response


def build_response(
    user_message: str,
    user_context: Optional[Dict] = None,
    intent: Optional[str] = None,
    confidence: Optional[float] = None,
) -> str:
    """
    Build complete bot response by orchestrating the full pipeline.

    Pipeline:
    1. Classify intent (skipped if intent is passed in)
    2. Extract entities
    3. Route to appropriate handler
    4. Handler fetches context and calls Gemini to generate response
    5. Falls back to hardcoded string if Gemini is unavailable

    Args:
        user_message: The user's input message.
        user_context: Optional context (user_id, conversation_id, etc.)
        intent: Pre-classified intent — if provided, skips the classify call.
        confidence: Confidence score matching the pre-classified intent.

    Returns:
        Formatted response string ready for WhatsApp.
    """
    if not user_message or not user_message.strip():
        return handle_unknown(user_message)

    try:
        if intent is None:
            intent_result = classify_intent(user_message)
            intent = intent_result["intent"]
            confidence = intent_result["confidence"]

        confidence = confidence or 0.0

        print(f"Intent: {intent}, Confidence: {confidence:.2f}")

        entities = extract_entities(user_message, intent)
        print(f"Entities: {entities}")

        if intent == "greeting":
            response = handle_greeting(user_context)
        elif intent == "faq_query":
            response = handle_faq_query(user_message, entities)
        elif intent == "event_query":
            response = handle_event_query(user_message, entities)
        elif intent == "donation_request":
            response = handle_donation(entities)
        elif intent == "directions_request":
            response = handle_directions(user_message, entities)
        else:
            response = handle_unknown(user_message)

        return response

    except Exception as e:
        print(f"Error in build_response: {e}")
        return "I'm experiencing technical difficulties. Please try again or contact the temple at (469) 606-3119."


if __name__ == "__main__":
    test_messages = [
        "Hello",
        "Where is the temple?",
        "What time is Friday satsang?",
        "How do I donate?",
        "Directions from Dallas",
        "What's the weather?",
    ]

    print("\n=== Response Builder Test ===\n")
    for message in test_messages:
        print(f"USER: {message}")
        print(f"BOT: {build_response(message)}")
        print("\n" + "=" * 50 + "\n")
